on:
  release:
    types: [created]

name: Build & release
jobs:
  releases-matrix:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: ["386", amd64, arm, arm64]
    steps:
      - uses: actions/checkout@v4

      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: "push-all"
          pre_command: export CGO_ENABLED=0
          asset_name: push-all-${{ matrix.goos }}-${{ matrix.goarch }}
          ldflags: -X "main.Version=${{ github.ref_name }}"
